project:
  type: website
  output-dir: _site
  execute-dir: project
  # pre-render: make download-images
  preview:
    port: 9999
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Version Control with Git"
  favicon: images/git-logo.png
  site-url: "https://lennartwittkuhn.com/version-control-course-zi-mannheim-2025/"
  repo-url: "https://github.com/lnnrtwttkhn/version-control-course-zi-mannheim-2025/"
  open-graph: false
  navbar:
    background: light
    title: false
    pinned: true
    left:
      - text: "{{< fa house >}} Home"
        href: index.qmd
      - text: "{{< fa circle-info >}} About"
        href: about.qmd
      - text: "{{< fa clipboard-list >}} Schedule"
        href: schedule.qmd
      - text: "{{< fa list-ol >}} Sessions"
        href: sessions/index.qmd
      - text: "{{< fa github >}} ZI-git"
        href: zi-git.qmd
      # - text: "{{< fa wrench >}} Tools"
      #   href: tools.qmd
      # - text: "{{< fa chalkboard-user >}} Team"
      #   href: team.qmd
      # - text: "{{< fa gem >}} Resources"
      #  href: resources.qmd
      # - text: "{{< fa gear >}} Mechanics"
      #   href: mechanics.qmd
      - text: "{{< fa handshake >}} Code of Conduct"
        href: code-of-conduct.qmd
      # - text: "{{< fa heart >}} Acknowledgements"
      #   href: acknowledgements.qmd
    right:
      - icon: envelope
        aria-label: Email
        href: "{{< var project.mailto >}}"
      - icon: github
        aria-label: GitHub
        href: "{{< var project.github >}}"

  page-footer:
    background: light
    border: true
    left: |
      Â© {{< var project.years >}} [Dr. Lennart Wittkuhn]({{< var team.lennart.website >}})
    # center:
    #   - text: "Acknowledgements"
    #     href: acknowledgements.qmd
    right: |
      License: [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

bibliography: references.bib
csl: apa-annotated-bibliography.csl

format:
  html:
    theme: [litera, custom.scss]
    from: markdown+emoji
    mainfont: "Atkinson Hyperlegible"
    page-layout: full
    fontcolor: black
    linkcolor: black
    link-external-newwindow: true
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    code-link: false
    code-copy: true
    code-overflow: wrap
    html-math-method: katex
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: tango
    include-after-body: plausible.html
